<?php
/**
 * This file is part of Herve_ConfigExampleMain for Magento.
 *
 * @license http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author Herve Guetin <herve.guetin@agence-soon.fr> <@herveguetin>
 * @category Herve
 * @package Herve_ConfigExampleMain
 */
/** @var Herve_ConfigExampleMain_Block_SimpleConfig $this */
?>
<div>
    <h4>A simple value coming from the config</h4>
    <?php echo $this->getSimpleConfigNodeValue() ?>
</div>